### ISSUE TITLE
Relies on non-major-version modules

### ISSUE THREAD

**Issue by phated** [jonschlinkert/array-initial#1]
Any chance these can all be updated? (I noticed array-slice has already been bumped to 1.0 and object.defaults relies on it).

Ref 
![screen shot 2017-08-01 at 1 20 02 pm](https://user-images.githubusercontent.com/992373/28845222-283d32d8-76bc-11e7-9c79-84989b098804.png)

**Comment by jonschlinkert** [comment]
@phated no problem, I can add you to all the repos if you want.

**Comment by jonschlinkert** [comment]
invite link https://github.com/jonschlinkert/array-initial/invitations
